version: '3.4'

services:

  reverse-proxy:
    image: traefik:v2.3
    container_name: reverse-proxy
    restart: always
    command: --api.insecure=true
    ports:
        - "80:80"
    volumes:
        - "./proxy-conf/traefik.yml:/etc/traefik/traefik.yml"
        - "./proxy-conf/dynamic/:/etc/traefik/traefik.d/"

  # NGINX service for fast-cgi
  nginx:
    image: nginx:1.15.5-alpine
    volumes:
      - './uber_heat_monolithe/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './uber_heat_monolithe:/app'

  # PHP-FPM service
  php:
    build:
      context: ./uber_heat_monolithe
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - './uber_heat_monolithe/:/app'
      - './uber_heat_monolithe/docker/php/fpm.conf:/usr/local/etc/php-fpm.conf:ro'
      - './uber_heat_monolithe/docker/php/php.ini:/usr/local/etc/php/php.ini:ro'

  # MYSQL service
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=symfony
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './uber_heat_monolithe/db:/var/lib/mysql'

    # MYSQL service
  front:
    build:
      context: ./uber_heat_front
      dockerfile: ./Dockerfile
    environment:
      - BACKEND_URL=nginx:80
    volumes:
      - './uber_heat_monolithe/db:/var/lib/mysql'


volumes:
  # DB save
  db: {}
